// Generated by Wrangler on Tue Jun 25 2024 02:49:30 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
    REDIRECT_URL: string;
    PASSWORD: string;
	DB: D1Database;
}
